name: SelfHosted Tester

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
        continue-on-error: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --no-deps -r RequirementsFiles/requirements.txt
          pip install --no-deps -r RequirementsFiles/requirements-cuda.txt
          pip install --no-deps -r RequirementsFiles/requirements-llama-cpp.txt
          pip install --no-deps -r RequirementsFiles/requirements-stable-diffusion-cpp.txt
        continue-on-error: true

      - name: Run tests
        run: |
          pytest LaunchFile/app.py
        continue-on-error: true
